# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'klienttest.ui'
#
# Created: Fri Mar 29 17:00:23 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Client(object):
    def setupUi(self, Client):
        Client.setObjectName(_fromUtf8("Client"))
        Client.resize(840, 593)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        Client.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/tree.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Client.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Client)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.formLayout = QtGui.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.list_modules = QtGui.QListWidget(self.centralwidget)
        self.list_modules.setObjectName(_fromUtf8("list_modules"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.list_modules)
        self.tabWidget_bas = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget_bas.sizePolicy().hasHeightForWidth())
        self.tabWidget_bas.setSizePolicy(sizePolicy)
        self.tabWidget_bas.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget_bas.setObjectName(_fromUtf8("tabWidget_bas"))
        self.tab_basic = QtGui.QWidget()
        self.tab_basic.setObjectName(_fromUtf8("tab_basic"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_basic)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formBas = QtGui.QFormLayout()
        self.formBas.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formBas.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formBas.setRowWrapPolicy(QtGui.QFormLayout.WrapLongRows)
        self.formBas.setSpacing(6)
        self.formBas.setObjectName(_fromUtf8("formBas"))
        self.verticalLayout.addLayout(self.formBas)
        self.tabWidget_bas.addTab(self.tab_basic, _fromUtf8(""))
        self.tab_advanced = QtGui.QWidget()
        self.tab_advanced.setObjectName(_fromUtf8("tab_advanced"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_advanced)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formAdv = QtGui.QFormLayout()
        self.formAdv.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formAdv.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formAdv.setRowWrapPolicy(QtGui.QFormLayout.WrapLongRows)
        self.formAdv.setObjectName(_fromUtf8("formAdv"))
        self.verticalLayout_2.addLayout(self.formAdv)
        self.tabWidget_bas.addTab(self.tab_advanced, _fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.tabWidget_bas)
        self.send_button = QtGui.QPushButton(self.centralwidget)
        self.send_button.setObjectName(_fromUtf8("send_button"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.send_button)
        Client.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Client)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPreferences = QtGui.QMenu(self.menubar)
        self.menuPreferences.setObjectName(_fromUtf8("menuPreferences"))
        self.menuConnection = QtGui.QMenu(self.menuPreferences)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/download_free_must_have_icon_set/must_have_icon_set/Globe/Globe_32x32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuConnection.setIcon(icon1)
        self.menuConnection.setObjectName(_fromUtf8("menuConnection"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        Client.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Client)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Client.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(Client)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/download_free_must_have_icon_set/must_have_icon_set/Delete/Delete_32x32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionOpen = QtGui.QAction(Client)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/download_free_must_have_icon_set/must_have_icon_set/Open/Open_32x32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon3)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionConnect = QtGui.QAction(Client)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/download_free_must_have_icon_set/must_have_icon_set/Next/Next_32x32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon4)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionDisconnect = QtGui.QAction(Client)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/download_free_must_have_icon_set/must_have_icon_set/Log Out/Log Out_32x32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisconnect.setIcon(icon5)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.actionAbout = QtGui.QAction(Client)
        self.actionAbout.setEnabled(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("icons/download_free_must_have_icon_set/must_have_icon_set/Information/Information_32x32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuConnection.addAction(self.actionConnect)
        self.menuConnection.addAction(self.actionDisconnect)
        self.menuPreferences.addAction(self.menuConnection.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Client)
        self.tabWidget_bas.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), Client.close)
        QtCore.QMetaObject.connectSlotsByName(Client)

    def retranslateUi(self, Client):
        Client.setWindowTitle(_translate("Client", "Client", None))
        self.tabWidget_bas.setTabText(self.tabWidget_bas.indexOf(self.tab_basic), _translate("Client", "Basic", None))
        self.tabWidget_bas.setTabText(self.tabWidget_bas.indexOf(self.tab_advanced), _translate("Client", "Advanced", None))
        self.send_button.setText(_translate("Client", "SEND", None))
        self.menuFile.setTitle(_translate("Client", "File", None))
        self.menuPreferences.setTitle(_translate("Client", "Preferences", None))
        self.menuConnection.setTitle(_translate("Client", "Connection", None))
        self.menuHelp.setTitle(_translate("Client", "Help", None))
        self.actionExit.setText(_translate("Client", "Exit", None))
        self.actionOpen.setText(_translate("Client", "Open", None))
        self.actionConnect.setText(_translate("Client", "Connect", None))
        self.actionDisconnect.setText(_translate("Client", "Disconnect", None))
        self.actionAbout.setText(_translate("Client", "About", None))

